package random;
import java.util.*;

public class Game {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
        Random rnum = new Random();
       Scanner sc = new Scanner(System.in);
          int random = rnum.nextInt(100);
          int n, count=1;
          System.out.println(random);
          System.out.println("\t\tWelcom to Siddharth's Tukkebaz Game");
          System.out.println();
          System.out.println("* In these game the comiler generate a random number,");
          System.out.println("  and you have to guess the number in minimum attemp.");
          System.out.println();
              
          System.out.print("Random number Generated by compiler is = ");
          System.out.println("**");
          System.out.println("\n These is your "+count+" Attemp");
          System.out.println("Enter your guessing Number");
             n = sc.nextInt();
             if(n<random){
            	 System.out.println("#Hint --> Enter bigger number");
             }
             else if(n>random){
            	 System.out.println("#Hint --> Enter Lower number");
             }
		  while(n !=random){
			  ++count;
			  System.out.println("\n These is your "+count+" Attemp");
	          System.out.println("Enter your guessing Number");
	             n = sc.nextInt();
	             if(n<random){
	            	 System.out.println("#Hint --> Enter bigger number");
	             }
	             else if(n>random){
	            	 System.out.println("#Hint --> Enter Lower number");
	             }	  
			  
			  
		  }
		if(n==random){
			System.out.println("Congrats you guess right number");
			System.out.println("Your total attemp is  "+count);
		}
		
		
		
		
	}

}
